export * from './persona';
export * from './jugador';
export * from './localidad';
export * from './nacionalidad';
export * from './provincia';
export * from './domicilio';
export * from './contacto';
export * from './tipo_documento';
export * from './estado_civil';